config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'
  post 'sessions/create'
  delete 'sessions/destroy'

  #get 'users/new'
  #post 'users/create'
  #get 'users/show'
  #get 'users/edit'
  #put 'users/update'
  #delete 'users/destroy'
  resources :users

  namespace :spotted do
    get 'artists/index'

    # albunst actions
    get 'albums/index/:artist_id', to: 'albums#index', as: :artist_albums_index
    resources :albums
    #get ':artist_id/albuns/edit/:id', to: 'albuns#edit', as: :albuns_edit
    #put ':artis_id/albuns/update/:id', to: 'albuns#update', as: :albuns_update
    #get 'albuns/new', 
    #post 'albuns/create'
    #delete 'albuns/destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  include ArtistsConcern

  validates :album_name, presence: true
  validates :year, presence: true

  def artist
    Artist.new(find_artist_by_id(artist_id))
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# File dedicated to implementing the base class of artist
class Artist
  extend ArtistsConcern

  attr_accessor :id, :twitter, :name

  def initialize(artist_hash)
    @id = artist_hash['id']
    @name = artist_hash['name']
    @twitter = artist_hash['twitter']
  end

  def self.all
    all_artists.map do |artist_hash|
      new(artist_hash)
    end
  end

  def self.find(id)
    new(find_artist_by_id(id))
  end

  def albums
    Album.where(artist_id: id)
  end

end

app/models/concerns/artists_concern.rb
# Concern dedicated to making request to the api
module ArtistsConcern
  extend ActiveSupport::Concern
  include HTTParty

  BASE_URI = 'https://moat.ai/api/task/'
  BASIC_HEADER = 'ZGV2ZWxvcGVyOlpHVjJaV3h2Y0dWeQ=='

  def all_artists
    http_response = HTTParty.get(BASE_URI, headers: { 'Basic': BASIC_HEADER })
    parsed_http_response = http_response&.parsed_response
    parsed_http_response&.map do |response_item|
      response_item[0]
    end
  end

  def find_artist_by_id(artist_id)
    http_response = HTTParty.get(BASE_URI + "?artist_id=#{artist_id}", headers: { 'Basic': BASIC_HEADER })
    http_response&.parsed_response.try(:[], 0)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :user_name, format: { with: /[A-Za-z_0-9]+/i }, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates :password, presence: true
  validates :role, presence: true

  enum role: { user: 0, admin: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  before_action :authorized?, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(user_name: user_params[:user_name])
    if !@user.nil? && @user.authenticate(user_params[:password])
      user_login @user
      redirect_to spotted_artists_index_path
    else
      @message = "Sorry, we couldn't find an account with this username. Please check you're using the right username and try again."
      respond_to do |format|
        format.js { render js: "alertify.alert(\"Login error\", \"#{@message}\")", layout: false }
      end
    end
  end

  def destroy
    user_logout
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(User.column_names - %i[id created_at updated_at password_digest],
                                 :password)
  end

end

app/controllers/spotted/albums_controller.rb
class Spotted::AlbumsController < Spotted::SpottedController
  def index
    @artist = Artist.find(params[:artist_id])
    @albums = @artist.albums
    @new_album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
    respond_to do |format|
      format.js do
        render 'spotted/albums/edit',
               locals: {
                 album: @album,
                 artist: @album.artist,
                 albums_action_path: spotted_album_path(@album),
                 method: :put
               }
      end
    end
  end

  def update
    @album = Album.find(params[:id])
    @artist = @album.artist
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @album.update(album_params)
          @albums = @artist.albums
          format.js { render 'spotted/albums/index', locals: { albums: @albums } }
        else
          format.js { render inline: "alertify.error(\"#{@album.errors.full_messages.join('\n')}\")" }
        end
      end
    end
  end

  def new
  end

  def create
    @new_album = Album.new(album_params)
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @new_album.save
          @albums = @new_album.artist.albums
          format.js { render 'spotted/albums/index', locals: { albums: @albums } }
        else
          format.js { render inline: "alertify.erro(\"#{@new_album.errors.full_messages.join('\n')}\")"}
        end
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @artist = @album.artist
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @album.delete
          @albums = @artist.albums
          format.js { render 'spotted/albums/index', locals: { albums: @albums } }
        else
          format.js { render inline: "alertify.erro(\"#{@album.errors.full_messages.join('\n')}\")"}
        end
      end
    end
  end

  private

  def album_params
    params.require(:album).permit(Album.column_names - %i[id created_at updated_at])
  end


end

app/controllers/spotted/artists_controller.rb
class Spotted::ArtistsController < Spotted::SpottedController
  def index
    @artists = Artist.all
  end
end

app/controllers/spotted/spotted_controller.rb
class Spotted::SpottedController < ApplicationController
  layout 'spotted'
  before_action :not_authorized?
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      user_login(@user)
      redirect_to spotted_artists_index_path
    else
      @error_message = @user.errors.full_messages.join('\n')
      render :create
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(User.column_names - %w[id created_at updated_at],
                                 %i[password password_confirmation])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #  Verifies if the user is logged in
  #
  # @return [Boolean] the logged in verification for user
  #
  def logged_in?
    if session[:user_id].present? and !session[:user_id].nil?
      true
    else
      false
    end
  end

  #
  # Returns the current user in the application
  #
  # @return [User] model User with the user data
  #
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authorized?
    redirect_to spotted_artists_index_path if logged_in?
  end

  def not_authorized?
    redirect_to root_path unless logged_in?
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Creates a session variable for user id
  #
  # @param [User] user The model object with user data
  #
  def user_login(user)
    session[:user_id] = user.id unless session[:user_id].present?
  end

  #
  # Removes the session variable containing the current user
  #
  def user_logout
    session.delete(:user_id)
  end

end

app/helpers/spotted/albuns_helper.rb
module Spotted::AlbunsHelper
end

app/helpers/spotted/artists_helper.rb
module Spotted::ArtistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Developertask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/spotted.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotted</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag params[:controller], 'data-turbolinks-track': 'reload', defer: true%>
  </head>
  <body>
    <section id="site-header">
      <div id="site-header-content" class="spotted-header">
        <%= link_to spotted_artists_index_path do %>
          <h1>Spotted</h1>
        <% end %>
      </div>
      <nav>
        <ul>
          <li>
            <%= link_to sessions_destroy_path, method: :delete, class: 'btn btn-primary' do %>
              <i class="fas fa-sign-out-alt"></i> Logout
            <% end %>
          </li>
        </ul>
      </nav>
      <div class="float-breaker"></div>
    </section>
    <%= yield %>
  </body>
</html>

app/views/spotted/albums/create.js.erb
<% albums_list = j render partial: 'spotted/albums/partials/albums_list', locals: { albums: albums }  %>
(function (){
  let albums_list = document.querySelector('.albums-list')
  if(albums_list){
    albums_list.innerHTML = '<%= albums_list %>'
  }
}).call(this)

app/views/spotted/albums/destroy.html.erb
<h1>Spotted::Albuns#destroy</h1>
<p>Find me in app/views/spotted/albuns/destroy.html.erb</p>

app/views/spotted/albums/edit.js.erb
<% modal_form_edit = j render(partial: 'spotted/albums/partials/album_modal_form', 
                              locals: { 
                                album: album, 
                                artist: artist, 
                                albums_action_path: albums_action_path,
                                method: method 
                              }, 
                              layout: false )%>
(function  () {
  let modal_form_edit_containter = document.querySelector('.modal-edit-container')
  if(modal_form_edit_containter){
    modal_form_edit_containter.innerHTML = '<%= modal_form_edit %>'
  }
}).call(this)

app/views/spotted/albums/index.html.erb
<section class="artist-data header-container">
  <h1><%= @artist.name %></h1>
  <p><%= @artist.twitter%></p>
</section>
<section class="create-new-album-action">
  <%= button_tag class: "btn btn-lg btn-create-new-album" do %>
    <i class="fas fa-plus"></i> Create new album
  <% end %>
</section>
<section class="albums-list">
  <%= render 'spotted/albums/partials/albums_list' %>
</section>
<section class="modal-new-album-container" style="display: inline;">
  <%= render 'spotted/albums/partials/album_modal_form', album: @new_album, artist: @artist, albums_action_path: spotted_albums_path, method: :post%>
</section>
<section class="modal-edit-container" style="display: inline;">
</section>

app/views/spotted/albums/index.js.erb
<% albums_list = j render partial: 'spotted/albums/partials/albums_list', locals: { albums: albums }  %>
(function (){
  let albums_list = document.querySelector('.albums-list')
  if(albums_list){
    albums_list.innerHTML = '<%= albums_list %>'
  }
}).call(this)

app/views/spotted/albums/new.html.erb
<h1>Spotted::Albuns#new</h1>
<p>Find me in app/views/spotted/albuns/new.html.erb</p>

app/views/spotted/albums/partials/_album_modal_form.html.erb
<div class="modal fade" id="modal-album" ariaLabeledBy="#modal-album" tab-index="-1" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        </div>
        <%= form_with model: album, url: albums_action_path, method: method, html: { 'data-remote': true } do |f| %>
          <div class="modal-body">
            <%= f.hidden_field :artist_id, value: artist.id %>
            <%= f.text_field :album_name, placeholder: "Album Name", required: true, class: 'form-control' %>
            <%= f.number_field :year, placeholder: "1994", required: true, class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <%= f.submit class: 'btn btn-success', 'data-bs-dismiss': 'modal' do %>
              Create album
            <% end %>
            <%= f.button type: :reset, class: 'btn btn-danger', 'data-bs-dismiss': 'modal' do %>
              <i class="fas fa-times" ></i> Cancel
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/spotted/albums/partials/_albums_list.html.erb
<% if !@albums.empty? %>
  <% @albums.each do |album| %>
    <div class="album-list-item">
      <div class="album-data">
        <div class="album-name">
          <h4><%= album.album_name %></h4>
        </div>
        <div class="album-year">
          <h6><%= album.year %></h6>
        </div>
      </div>
      <div class="album-actions">
        <%= link_to edit_spotted_album_path(album.id), class: 'btn btn-outline-light', remote: true do  %>
          <i class="fas fa-edit"></i>
        <% end %>
        <% if current_user.role == 'admin'%>
          <%= link_to spotted_album_path(album.id), class: 'btn btn-outline-light', method: :delete, remote: true do  %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      </div>
      <div class="float-breaker"></div>
    </div>
  <% end %>
<% else %>
  <div class="album-list-item">
    <h1>No album to display</h1>
  </div>
<% end %>

app/views/spotted/artists/index.html.erb
<section id="artist-list">
  <% @artists.each do |artist| %>
    <%= link_to spotted_artist_albums_index_path(artist.id), class: 'link-to-artist' do %>
      <div class="artist-list-item">
        <h5 class="artist-name"><%= artist.name %></h5>
        <div class="artist-twitter">
          <p><%= artist.twitter %></p>
        </div> 
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/create.js.erb
<% error_message = j render inline: "<div class=\"alert alert-danger\">#{@error_message}</div>"%>
alertify.error('<%= error_message %>')

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="form-login-signup-container">
  <h1 class="app-name">Spotted</h1>
  <div class="fields-container">
    <%= form_with model: @user, method: :post, html: { 'data-remote': true } do |f| %> 
      <div class="field-container">
        <%= f.text_field :full_name, placeholder: 'Your full name', required: true, class: 'form-control' %>
      </div>
      <div class="field-container">
        <%= f.text_field :user_name, placeholder: 'Your username', required: true, class: 'form-control' %>
      </div>
      <div class="field-container">
        <%= f.password_field :password, placeholder: 'Your password', required: true, class: 'form-control' %>
      </div>
      <div class="field-container">
        <%= f.password_field :password_confirmation, placeholder: 'Your password confirmation', required: true, class: 'form-control' %>
      </div>
      <div>
        <div>
          <%= f.label :role, 'user:'%>
          <%= f.radio_button :role, :user, checked: true %>
        </div>
        <div>
          <%= f.label :role, 'admin:'%>
          <%= f.radio_button :role, :admin %>
        </div>
      </div>
      <div>
        <%= link_to root_path, class: 'btn btn-primary' do %>
          Return
        <% end  %>
        <%= f.button 'Clear', type: :reset, class: 'btn btn-warning' %>
        <%= f.submit 'Register', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>